version: 2

references:
  container_config: &container_config
    docker:
      - image: circleci/node:10
    working_directory: ~/portals-wrapper

  attach_workspace: &attach_workspace
    attach_workspace:
      at: ~/portals-wrapper

jobs:
  setup:
    <<: *container_config
    steps:
      - checkout
      - run: node -v
      - run: npm -v
      - run: npm install
      - run:
          command: |
            set +eo
            npm ls
            true
      - persist_to_workspace:
          root: ~/portals-wrapper
          paths:
            - node_modules
  lint:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run: npm run lint
  test:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run: npm test
      - run: bash <(curl -s https://codecov.io/bash) -t 7bf05ba0-5e4e-42f0-bb9a-04111a94e629
workflows:
  version: 2
  build:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - test:
          requires:
            - setup
